% -------------------------------------------------------------------
%  Generated by MATLAB on 3-Mar-2017 15:12:47
%  MATLAB version: 8.5.0.197613 (R2015a)
% -------------------------------------------------------------------
saveVarsMat = load('f.mat');

A = saveVarsMat.A; % <1080x1920x3 uint8> too many elements

AS = saveVarsMat.AS; % <1080x1920x3 uint8> too many elements

B = saveVarsMat.B; % <1072x1920 double> too many elements

Bq = saveVarsMat.Bq; % <1072x1920 double> too many elements

Number_Pixels = 6.2208E+6;

blockSize = 16;

c = 1920;

colSize = 1920;

columns = 5760;

count = 8041;

i = 1079;

img = saveVarsMat.img; % <1080x1920 double> too many elements

img1 = saveVarsMat.img1; % <1080x1920 double> too many elements

img2 = saveVarsMat.img2; % <1080x1920 double> too many elements

j = 1919;

jump = 15;

k = 1080;

l = 1920;

printLimit = 16;

r = 1080;

rowSize = 1080;

rows = 1080;

s = saveVarsMat.s; % <1080x1920x3 int16> too many elements

sum = 184;

zigzag = saveVarsMat.zigzag; % <8040x256 double> too many elements

zzcount = 256;

clear saveVarsMat;
